package org.drools.agentvalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agency implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String tin;
	private java.lang.Long effDate;
	private java.lang.Long termDate;
	private java.lang.String useIND;
	private java.lang.String validationStatus = "Validation Failed";

	public Agency() {
	}

	public java.lang.String getTin() {
		return this.tin;
	}

	public void setTin(java.lang.String tin) {
		this.tin = tin;
	}

	public java.lang.Long getEffDate() {
		return this.effDate;
	}

	public void setEffDate(java.lang.Long effDate) {
		this.effDate = effDate;
	}

	public java.lang.Long getTermDate() {
		return this.termDate;
	}

	public void setTermDate(java.lang.Long termDate) {
		this.termDate = termDate;
	}

	public java.lang.String getUseIND() {
		return this.useIND;
	}

	public void setUseIND(java.lang.String useIND) {
		this.useIND = useIND;
	}

	public java.lang.String getValidationStatus() {
		return this.validationStatus;
	}

	public void setValidationStatus(java.lang.String validationStatus) {
		this.validationStatus = validationStatus;
	}

	

	public Agency(java.lang.String tin, java.lang.Long effDate,
			java.lang.Long termDate, java.lang.String useIND,
			java.lang.String validationStatus) {
		this.tin = tin;
		this.effDate = effDate;
		this.termDate = termDate;
		this.useIND = useIND;
		this.validationStatus = validationStatus;
	}

}