package org.drools.agentvalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgentWritingTIN implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	private boolean isAgentWritingTINValid;

	private String isAgentProducerWritingTinValid = "false";
	private java.util.List<org.drools.agentvalidation.Producer> producerRecordList;

	private String isAgentLicenseWritingTinValid = "false";
	private java.util.List<org.drools.agentvalidation.License> licenseRecordList;

	private String isAgentAgencyWritingTinValid = "false";
	private java.util.List<org.drools.agentvalidation.Agency> agencyRecordList;

	private String isAgentAppointmentWritingTinValid = "false";
	private java.util.List<org.drools.agentvalidation.Appointment> appointmentRecordList;

	private String isAgentCertificationWritingTinValid = "false";
	private java.util.List<org.drools.agentvalidation.Certification> certificationRecordList;

	public AgentWritingTIN() {
	}

	public java.util.List<org.drools.agentvalidation.Producer> getProducerRecordList() {
		return this.producerRecordList;
	}

	public void setProducerRecordList(
			java.util.List<org.drools.agentvalidation.Producer> producerRecordList) {
		this.producerRecordList = producerRecordList;
	}

	public java.util.List<org.drools.agentvalidation.License> getLicenseRecordList() {
		return this.licenseRecordList;
	}

	public void setLicenseRecordList(
			java.util.List<org.drools.agentvalidation.License> licenseRecordList) {
		this.licenseRecordList = licenseRecordList;
	}

	public java.util.List<org.drools.agentvalidation.Agency> getAgencyRecordList() {
		return this.agencyRecordList;
	}

	public void setAgencyRecordList(
			java.util.List<org.drools.agentvalidation.Agency> agencyRecordList) {
		this.agencyRecordList = agencyRecordList;
	}

	public java.util.List<org.drools.agentvalidation.Appointment> getAppointmentRecordList() {
		return this.appointmentRecordList;
	}

	public void setAppointmentRecordList(
			java.util.List<org.drools.agentvalidation.Appointment> appointmentRecordList) {
		this.appointmentRecordList = appointmentRecordList;
	}

	public java.util.List<org.drools.agentvalidation.Certification> getCertificationRecordList() {
		return this.certificationRecordList;
	}

	public void setCertificationRecordList(
			java.util.List<org.drools.agentvalidation.Certification> certificationRecordList) {
		this.certificationRecordList = certificationRecordList;
	}

	public boolean isIsAgentWritingTINValid() {
		return this.isAgentWritingTINValid;
	}

	public void setIsAgentWritingTINValid(boolean isAgentWritingTINValid) {
		this.isAgentWritingTINValid = isAgentWritingTINValid;
	}

	public AgentWritingTIN(
			java.util.List<org.drools.agentvalidation.Producer> producerRecordList,
			java.util.List<org.drools.agentvalidation.License> licenseRecordList,
			java.util.List<org.drools.agentvalidation.Agency> agencyRecordList,
			java.util.List<org.drools.agentvalidation.Appointment> appointmentRecordList,
			java.util.List<org.drools.agentvalidation.Certification> certificationRecordList) {
		this.producerRecordList = producerRecordList;
		this.licenseRecordList = licenseRecordList;
		this.agencyRecordList = agencyRecordList;
		this.appointmentRecordList = appointmentRecordList;
		this.certificationRecordList = certificationRecordList;

	}

	public java.lang.String getIsAgentAgencyWritingTinValid() {
		return this.isAgentAgencyWritingTinValid;
	}

	public void setIsAgentAgencyWritingTinValid(
			java.lang.String isAgentAgencyWritingTinValid) {
		this.isAgentAgencyWritingTinValid = isAgentAgencyWritingTinValid;
	}

	public java.lang.String getIsAgentProducerWritingTinValid() {
		return this.isAgentProducerWritingTinValid;
	}

	public void setIsAgentProducerWritingTinValid(
			java.lang.String isAgentProducerWritingTinValid) {
		this.isAgentProducerWritingTinValid = isAgentProducerWritingTinValid;
	}

	public java.lang.String getIsAgentLicenseWritingTinValid() {
		return this.isAgentLicenseWritingTinValid;
	}

	public void setIsAgentLicenseWritingTinValid(
			java.lang.String isAgentLicenseWritingTinValid) {
		this.isAgentLicenseWritingTinValid = isAgentLicenseWritingTinValid;
	}

	public java.lang.String getIsAgentAppointmentWritingTinValid() {
		return this.isAgentAppointmentWritingTinValid;
	}

	public void setIsAgentAppointmentWritingTinValid(
			java.lang.String isAgentAppointmentWritingTinValid) {
		this.isAgentAppointmentWritingTinValid = isAgentAppointmentWritingTinValid;
	}

	public java.lang.String getIsAgentCertificationWritingTinValid() {
		return this.isAgentCertificationWritingTinValid;
	}

	public void setIsAgentCertificationWritingTinValid(
			java.lang.String isAgentCertificationWritingTinValid) {
		this.isAgentCertificationWritingTinValid = isAgentCertificationWritingTinValid;
	}



}