package org.drools.agentvalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Certification implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String tin;

	private java.lang.String recID;

	private Long termDate;

	private java.lang.String co_cde;

	private Integer bnft_yr;

	private java.lang.String state;

	private java.lang.Long lst_uptd_ts;

	private java.lang.String prdt_cde;

	private java.lang.Long effDate;
	private java.lang.String validationStatus = "Validation Failed";

	public Certification() {
	}

	public java.lang.String getTin() {
		return this.tin;
	}

	public void setTin(java.lang.String tin) {
		this.tin = tin;
	}

	public java.lang.String getRecID() {
		return this.recID;
	}

	public void setRecID(java.lang.String recID) {
		this.recID = recID;
	}

	public java.lang.Long getTermDate() {
		return this.termDate;
	}

	public void setTermDate(java.lang.Long termDate) {
		this.termDate = termDate;
	}

	public java.lang.String getCo_cde() {
		return this.co_cde;
	}

	public void setCo_cde(java.lang.String co_cde) {
		this.co_cde = co_cde;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.Long getLst_uptd_ts() {
		return this.lst_uptd_ts;
	}

	public void setLst_uptd_ts(java.lang.Long lst_uptd_ts) {
		this.lst_uptd_ts = lst_uptd_ts;
	}

	public java.lang.String getPrdt_cde() {
		return this.prdt_cde;
	}

	public void setPrdt_cde(java.lang.String prdt_cde) {
		this.prdt_cde = prdt_cde;
	}

	public java.lang.Long getEffDate() {
		return this.effDate;
	}

	public void setEffDate(java.lang.Long effDate) {
		this.effDate = effDate;
	}

	public java.lang.Integer getBnft_yr() {
		return this.bnft_yr;
	}

	public void setBnft_yr(java.lang.Integer bnft_yr) {
		this.bnft_yr = bnft_yr;
	}

	public java.lang.String getValidationStatus() {
		return this.validationStatus;
	}

	public void setValidationStatus(java.lang.String validationStatus) {
		this.validationStatus = validationStatus;
	}

	

	public Certification(java.lang.String tin, java.lang.String recID,
			java.lang.Long termDate, java.lang.String co_cde,
			java.lang.Integer bnft_yr, java.lang.String state,
			java.lang.Long lst_uptd_ts, java.lang.String prdt_cde,
			java.lang.Long effDate, java.lang.String validationStatus) {
		this.tin = tin;
		this.recID = recID;
		this.termDate = termDate;
		this.co_cde = co_cde;
		this.bnft_yr = bnft_yr;
		this.state = state;
		this.lst_uptd_ts = lst_uptd_ts;
		this.prdt_cde = prdt_cde;
		this.effDate = effDate;
		this.validationStatus = validationStatus;
	}

}