package org.drools.agentvalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgentParentTIN implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean isAgentParentTINValid;
	private String isAgentProducerParentTinValid = "false";
	private java.util.List<org.drools.agentvalidation.Producer> producerRecordList;

	private String isAgentLicenseParentTinValid = "false";
	private java.util.List<org.drools.agentvalidation.License> licenseRecordList;

	private String isAgentAgencyParentTinValid = "false";
	private java.util.List<org.drools.agentvalidation.Agency> agencyRecordList;

	private String isAgentAppointmentParentTinValid = "false";
	private java.util.List<org.drools.agentvalidation.Appointment> appointmentRecordList;

	private String isAgentCertificationParentTinValid = "false";
	private java.util.List<org.drools.agentvalidation.Certification> certificationRecordList = new java.util.ArrayList();

	public AgentParentTIN() {
	}

	public java.util.List<org.drools.agentvalidation.Producer> getProducerRecordList() {
		return this.producerRecordList;
	}

	public void setProducerRecordList(
			java.util.List<org.drools.agentvalidation.Producer> producerRecordList) {
		this.producerRecordList = producerRecordList;
	}

	public java.util.List<org.drools.agentvalidation.License> getLicenseRecordList() {
		return this.licenseRecordList;
	}

	public void setLicenseRecordList(
			java.util.List<org.drools.agentvalidation.License> licenseRecordList) {
		this.licenseRecordList = licenseRecordList;
	}

	public java.util.List<org.drools.agentvalidation.Agency> getAgencyRecordList() {
		return this.agencyRecordList;
	}

	public void setAgencyRecordList(
			java.util.List<org.drools.agentvalidation.Agency> agencyRecordList) {
		this.agencyRecordList = agencyRecordList;
	}

	public java.util.List<org.drools.agentvalidation.Appointment> getAppointmentRecordList() {
		return this.appointmentRecordList;
	}

	public void setAppointmentRecordList(
			java.util.List<org.drools.agentvalidation.Appointment> appointmentRecordList) {
		this.appointmentRecordList = appointmentRecordList;
	}

	public java.util.List<org.drools.agentvalidation.Certification> getCertificationRecordList() {
		return this.certificationRecordList;
	}

	public void setCertificationRecordList(
			java.util.List<org.drools.agentvalidation.Certification> certificationRecordList) {
		this.certificationRecordList = certificationRecordList;
	}

	public AgentParentTIN(
			java.util.List<org.drools.agentvalidation.Producer> producerRecordList,
			java.util.List<org.drools.agentvalidation.License> licenseRecordList,
			java.util.List<org.drools.agentvalidation.Agency> agencyRecordList,
			java.util.List<org.drools.agentvalidation.Appointment> appointmentRecordList,
			java.util.List<org.drools.agentvalidation.Certification> certificationRecordList) {
		this.producerRecordList = producerRecordList;
		this.licenseRecordList = licenseRecordList;
		this.agencyRecordList = agencyRecordList;
		this.appointmentRecordList = appointmentRecordList;
		this.certificationRecordList = certificationRecordList;

	}

	public java.lang.String getIsAgentCertificationParentTinValid() {
		return this.isAgentCertificationParentTinValid;
	}

	public void setIsAgentCertificationParentTinValid(
			java.lang.String isAgentCertificationParentTinValid) {
		this.isAgentCertificationParentTinValid = isAgentCertificationParentTinValid;
	}

	public java.lang.String getIsAgentLicenseParentTinValid() {
		return this.isAgentLicenseParentTinValid;
	}

	public void setIsAgentLicenseParentTinValid(
			java.lang.String isAgentLicenseParentTinValid) {
		this.isAgentLicenseParentTinValid = isAgentLicenseParentTinValid;
	}

	public java.lang.String getIsAgentAgencyParentTinValid() {
		return this.isAgentAgencyParentTinValid;
	}

	public void setIsAgentAgencyParentTinValid(
			java.lang.String isAgentAgencyParentTinValid) {
		this.isAgentAgencyParentTinValid = isAgentAgencyParentTinValid;
	}

	public java.lang.String getIsAgentAppointmentParentTinValid() {
		return this.isAgentAppointmentParentTinValid;
	}

	public void setIsAgentAppointmentParentTinValid(
			java.lang.String isAgentAppointmentParentTinValid) {
		this.isAgentAppointmentParentTinValid = isAgentAppointmentParentTinValid;
	}

	public boolean isIsAgentParentTINValid() {
		return this.isAgentParentTINValid;
	}

	public void setIsAgentParentTINValid(boolean isAgentParentTINValid) {
		this.isAgentParentTINValid = isAgentParentTINValid;
	}

	public java.lang.String getIsAgentProducerParentTinValid() {
		return this.isAgentProducerParentTinValid;
	}

	public void setIsAgentProducerParentTinValid(
			java.lang.String isAgentProducerParentTinValid) {
		this.isAgentProducerParentTinValid = isAgentProducerParentTinValid;
	}

	
}
