package org.drools.agentvalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean isAgentValid;

	public Agent() {
	}

	public boolean isIsAgentValid() {
		return this.isAgentValid;
	}

	public void setIsAgentValid(boolean isAgentValid) {
		this.isAgentValid = isAgentValid;
	}

	public Agent(boolean isAgentValid) {
		this.isAgentValid = isAgentValid;
	}

}