package org.drools.agentvalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Appointment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String tin;

	private java.lang.String recID;

	private Long termDate;

	private java.lang.Long apptDate;

	private java.lang.String co_cde;

	private java.lang.String state;

	private java.lang.Long trmtn_no_rnwl_dte;

	private java.lang.Long trmtn_wth_rnwl_dte;
	private java.lang.String validationStatus = "Validation Failed";

	public Appointment() {
	}

	public java.lang.String getTin() {
		return this.tin;
	}

	public void setTin(java.lang.String tin) {
		this.tin = tin;
	}

	public java.lang.String getRecID() {
		return this.recID;
	}

	public void setRecID(java.lang.String recID) {
		this.recID = recID;
	}

	public java.lang.Long getTermDate() {
		return this.termDate;
	}

	public void setTermDate(java.lang.Long termDate) {
		this.termDate = termDate;
	}

	public java.lang.Long getApptDate() {
		return this.apptDate;
	}

	public void setApptDate(java.lang.Long apptDate) {
		this.apptDate = apptDate;
	}

	public java.lang.String getCo_cde() {
		return this.co_cde;
	}

	public void setCo_cde(java.lang.String co_cde) {
		this.co_cde = co_cde;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.Long getTrmtn_no_rnwl_dte() {
		return this.trmtn_no_rnwl_dte;
	}

	public void setTrmtn_no_rnwl_dte(java.lang.Long trmtn_no_rnwl_dte) {
		this.trmtn_no_rnwl_dte = trmtn_no_rnwl_dte;
	}

	public java.lang.Long getTrmtn_wth_rnwl_dte() {
		return this.trmtn_wth_rnwl_dte;
	}

	public void setTrmtn_wth_rnwl_dte(java.lang.Long trmtn_wth_rnwl_dte) {
		this.trmtn_wth_rnwl_dte = trmtn_wth_rnwl_dte;
	}

	public java.lang.String getValidationStatus() {
		return this.validationStatus;
	}

	public void setValidationStatus(java.lang.String validationStatus) {
		this.validationStatus = validationStatus;
	}

	

	public Appointment(java.lang.String tin, java.lang.String recID,
			java.lang.Long termDate, java.lang.Long apptDate,
			java.lang.String co_cde, java.lang.String state,
			java.lang.Long trmtn_no_rnwl_dte,
			java.lang.Long trmtn_wth_rnwl_dte, java.lang.String validationStatus) {
		this.tin = tin;
		this.recID = recID;
		this.termDate = termDate;
		this.apptDate = apptDate;
		this.co_cde = co_cde;
		this.state = state;
		this.trmtn_no_rnwl_dte = trmtn_no_rnwl_dte;
		this.trmtn_wth_rnwl_dte = trmtn_wth_rnwl_dte;
		this.validationStatus = validationStatus;
	}

}