package org.drools.agentvalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class License implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long effDate;

	private java.lang.String tin;

	private java.lang.String recID;

	private Long termDate;

	private java.lang.String state;
	private java.lang.String validationStatus = "Validation Failed";

	public License() {
	}

	public java.lang.String getTin() {
		return this.tin;
	}

	public void setTin(java.lang.String tin) {
		this.tin = tin;
	}

	public java.lang.String getRecID() {
		return this.recID;
	}

	public void setRecID(java.lang.String recID) {
		this.recID = recID;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.Long getEffDate() {
		return this.effDate;
	}

	public void setEffDate(java.lang.Long effDate) {
		this.effDate = effDate;
	}

	public java.lang.Long getTermDate() {
		return this.termDate;
	}

	public void setTermDate(java.lang.Long termDate) {
		this.termDate = termDate;
	}

	public java.lang.String getValidationStatus() {
		return this.validationStatus;
	}

	public void setValidationStatus(java.lang.String validationStatus) {
		this.validationStatus = validationStatus;
	}



	public License(java.lang.Long effDate, java.lang.String tin,
			java.lang.String recID, java.lang.Long termDate,
			java.lang.String state, java.lang.String validationStatus) {
		this.effDate = effDate;
		this.tin = tin;
		this.recID = recID;
		this.termDate = termDate;
		this.state = state;
		this.validationStatus = validationStatus;
	}

}