package org.drools.agentvalidation;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Policy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String mbu;
	private Long effDate;
	private java.lang.String parentTIN;
	private java.lang.String systemID;
	private java.lang.String eventType;
	private java.lang.String writingTIN;
	private Long noNewBusinessDate;
	private java.lang.String state;
	private Long termDate;

	private java.lang.String paidTIN;

	private java.lang.String prodType;

	private java.lang.String cms_prdt_cde;

	private java.lang.String policyNumber;

	private String co_cde;

	public Policy() {
	}

	public java.lang.String getMbu() {
		return this.mbu;
	}

	public void setMbu(java.lang.String mbu) {
		this.mbu = mbu;
	}

	public java.lang.String getParentTIN() {
		return this.parentTIN;
	}

	public void setParentTIN(java.lang.String parentTIN) {
		this.parentTIN = parentTIN;
	}

	public java.lang.String getSystemID() {
		return this.systemID;
	}

	public void setSystemID(java.lang.String systemID) {
		this.systemID = systemID;
	}

	public java.lang.String getEventType() {
		return this.eventType;
	}

	public void setEventType(java.lang.String eventType) {
		this.eventType = eventType;
	}

	public java.lang.String getWritingTIN() {
		return this.writingTIN;
	}

	public void setWritingTIN(java.lang.String writingTIN) {
		this.writingTIN = writingTIN;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.Long getEffDate() {
		return this.effDate;
	}

	public void setEffDate(java.lang.Long effDate) {
		this.effDate = effDate;
	}

	public java.lang.Long getNoNewBusinessDate() {
		return this.noNewBusinessDate;
	}

	public void setNoNewBusinessDate(java.lang.Long noNewBusinessDate) {
		this.noNewBusinessDate = noNewBusinessDate;
	}

	public java.lang.Long getTermDate() {
		return this.termDate;
	}

	public void setTermDate(java.lang.Long termDate) {
		this.termDate = termDate;
	}

	public java.lang.String getPaidTIN() {
		return this.paidTIN;
	}

	public void setPaidTIN(java.lang.String paidTIN) {
		this.paidTIN = paidTIN;
	}

	public java.lang.String getProdType() {
		return this.prodType;
	}

	public void setProdType(java.lang.String prodType) {
		this.prodType = prodType;
	}

	public java.lang.String getCms_prdt_cde() {
		return this.cms_prdt_cde;
	}

	public void setCms_prdt_cde(java.lang.String cms_prdt_cde) {
		this.cms_prdt_cde = cms_prdt_cde;
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public java.lang.String getCo_cde() {
		return this.co_cde;
	}

	public void setCo_cde(java.lang.String co_cde) {
		this.co_cde = co_cde;
	}

	public Policy(java.lang.String mbu, java.lang.Long effDate,
			java.lang.String parentTIN, java.lang.String systemID,
			java.lang.String eventType, java.lang.String writingTIN,
			java.lang.Long noNewBusinessDate, java.lang.String state,
			java.lang.Long termDate, java.lang.String paidTIN,
			java.lang.String prodType, java.lang.String cms_prdt_cde,
			java.lang.String policyNumber, java.lang.String co_cde) {
		this.mbu = mbu;
		this.effDate = effDate;
		this.parentTIN = parentTIN;
		this.systemID = systemID;
		this.eventType = eventType;
		this.writingTIN = writingTIN;
		this.noNewBusinessDate = noNewBusinessDate;
		this.state = state;
		this.termDate = termDate;
		this.paidTIN = paidTIN;
		this.prodType = prodType;
		this.cms_prdt_cde = cms_prdt_cde;
		this.policyNumber = policyNumber;
		this.co_cde = co_cde;
	}

}