package org.drools.agentvalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Producer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long effDate;

	private java.lang.String tin;

	private Long noNewBusinessDate;

	private java.lang.String recID;

	private Long termDate;

	private java.lang.String validationStatus = "Validation failed";

	public Producer() {
	}

	public java.lang.String getTin() {
		return this.tin;
	}

	public void setTin(java.lang.String tin) {
		this.tin = tin;
	}

	public java.lang.String getRecID() {
		return this.recID;
	}

	public void setRecID(java.lang.String recID) {
		this.recID = recID;
	}

	public java.lang.Long getEffDate() {
		return this.effDate;
	}

	public void setEffDate(java.lang.Long effDate) {
		this.effDate = effDate;
	}

	public java.lang.Long getTermDate() {
		return this.termDate;
	}

	public void setTermDate(java.lang.Long termDate) {
		this.termDate = termDate;
	}

	public java.lang.Long getNoNewBusinessDate() {
		return this.noNewBusinessDate;
	}

	public void setNoNewBusinessDate(java.lang.Long noNewBusinessDate) {
		this.noNewBusinessDate = noNewBusinessDate;
	}

	public java.lang.String getValidationStatus() {
		return this.validationStatus;
	}

	public void setValidationStatus(java.lang.String validationStatus) {
		this.validationStatus = validationStatus;
	}

	public Producer(java.lang.Long effDate, java.lang.String tin,
			java.lang.Long noNewBusinessDate, java.lang.String recID,
			java.lang.Long termDate, java.lang.String validationStatus) {
		this.effDate = effDate;
		this.tin = tin;
		this.noNewBusinessDate = noNewBusinessDate;
		this.recID = recID;
		this.termDate = termDate;
		this.validationStatus = validationStatus;
	}

}